# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experience.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='experience.proto',
  package='',
  serialized_pb=_b('\n\x10\x65xperience.proto\"l\n\nExperience\x12\r\n\x05state\x18\x01 \x03(\x01\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\x12\x0e\n\x06reward\x18\x03 \x01(\x01\x12\x11\n\tnew_state\x18\x04 \x03(\x01\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x12\x0e\n\x06is_won\x18\x06 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXPERIENCE = _descriptor.Descriptor(
  name='Experience',
  full_name='Experience',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='Experience.state', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='Experience.action', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward', full_name='Experience.reward', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_state', full_name='Experience.new_state', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='done', full_name='Experience.done', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_won', full_name='Experience.is_won', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['Experience'] = _EXPERIENCE

Experience = _reflection.GeneratedProtocolMessageType('Experience', (_message.Message,), dict(
  DESCRIPTOR = _EXPERIENCE,
  __module__ = 'experience_pb2'
  # @@protoc_insertion_point(class_scope:Experience)
  ))
_sym_db.RegisterMessage(Experience)


# @@protoc_insertion_point(module_scope)
